version: "3.8"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - react
      - node
      - redis
  react:
    container_name: react
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    volumes:
      - ./src:/app:delegated
    command: ["npm", "run", "dev", "--", "--host", "--port", "3000"]
    ports:
      - "3000:3000"
  node:
    container_name: node
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    command: ["node", "server.js", "--port", "4444"]
    ports:
      - "4444:4444"
    environment:
      - PORT=4444
      - REDIS_URL=redis://redis:6379
      - TICK_RATE=20
  npm:
    container_name: npm
    image: node:22-slim
    working_dir: /app
    entrypoint: ["npm"]
    volumes:
      - ./src:/app
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data