name: Java CI with Maven

on:
  push:
    branches: [ main, master, development ]
  pull_request:
    branches: [ main, master, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean compile

    - name: Run tests
      run: mvn -B test
      continue-on-error: true

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: '**/surefire-reports/TEST-*.xml'
        reporter: java-junit
        fail-on-error: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/surefire-reports/*.xml
          **/surefire-reports/*.txt

    - name: Package application
      if: success()
      run: mvn -B package -DskipTests

